### ISSUE TITLE
power driver build  error fix that

### ISSUE THREAD

**Issue by muralivijay** [zoggn/oreo_kernel_lenovo_a2010#1]
scripts/Makefile.clean:17: drivers/misc/mediatek/base/power/mt2701_dcm/Makefile: No such file or directory
make[6]: *** No rule to make target 'drivers/misc/mediatek/base/power/mt2701_dcm/Makefile'.  Stop.
scripts/Makefile.clean:92: recipe for target 'drivers/misc/mediatek/base/power/mt2701_dcm' failed
make[5]: *** [drivers/misc/mediatek/base/power/mt2701_dcm] Error 2
scripts/Makefile.clean:92: recipe for target 'drivers/misc/mediatek/base/power' failed
make[4]: *** [drivers/misc/mediatek/base/power] Error 2
scripts/Makefile.clean:92: recipe for target 'drivers/misc/mediatek/base' failed
make[3]: *** [drivers/misc/mediatek/base] Error 2
scripts/Makefile.clean:92: recipe for target 'drivers/misc/mediatek' failed
make[2]: *** [drivers/misc/mediatek] Error 2
scripts/Makefile.clean:92: recipe for target 'drivers/misc' failed
make[1]: *** [drivers/misc] Error 2
Makefile:1205: recipe for target '_clean_drivers' failed
make: *** [_clean_drivers] Error 2

**Comment by zoggn** [comment]
This is kernel source for lenovo a2010(mt6735).  And for this platform with my defconfig it builds succesfully. If you want to build it for other platform or set of drivers you have to adopt it by yourself.

**Comment by muralivijay** [comment]
Actually i tried to build for my Lenovo a2010-a . Both are same model right ? . which defconfig are you used to build kernel ?

**Comment by muralivijay** [comment]
Did kernel boots ? Any bugs there ?

**Comment by zoggn** [comment]
Yes, it boots but some bugs still persist. Doesnt remember. Cameras doesnt work at all and something else. /arm/../a2010_oreo_defconfig is used.

**Comment by muralivijay** [comment]
thanks finally your oreo kernel source only boots well. why stock lenovo 3.10.65 not booting ? do you have any bootable 3.10.65 source code ?

**Comment by zoggn** [comment]
bcoz its not stock sources, lol. its a garbage from lenovo. And no, i dont have any other kernels for a2010
